# Generated by Django 4.2.7 on 2023-12-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='type',
            field=models.CharField(default='admin', max_length=20),
            preserve_default=False,
        ),
    ]
