# Generated by Django 4.2.5 on 2023-12-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_employee_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='model',
            field=models.CharField(default='car', max_length=255),
            preserve_default=False,
        ),
    ]
