# Generated by Django 5.0 on 2023-12-12 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_auto_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.parkingplace', unique=True),
        ),
    ]
